### ISSUE TITLE
File with space or accents are not displayed

### ISSUE THREAD

**Issue by rimeno** [wojciechkepka/gomd#4]
Interesting project, but I have some file with accents, and I test with space, same error : blank page

**Comment by wojciechkepka** [comment]
Thanks for checking it out. Would it be possible for you to provide an example to reporoduce this issue?

**Comment by wojciechkepka** [comment]
Try the master branch now. I've fixed some issues that might have caused your problems.

**Comment by rimeno** [comment]
$ pacman -Q | grep gomd
gomd-git 20200722.b89a6b0-1

Still have the same problems : 
"file with space.md" and "accentué.md" are indexed but can't be shown.

**Comment by wojciechkepka** [comment]
I'm pretty sure commit 2da03f6 fixed your issue. I've tested on my system and both `file with space.md` and `accentueé.md` worked now.

**Comment by rimeno** [comment]
Confirmed !
Thanks !

**Comment by wojciechkepka** [comment]
Awesome!
